# Generated by Django 4.0.6 on 2022-08-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
