# Generated by Django 4.0.6 on 2022-08-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uid',
        ),
    ]
