# Generated by Django 4.0.4 on 2022-08-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
        ('blog', '0012_remove_post_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uid',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.bloguser'),
        ),
    ]
