# Generated by Django 4.0.4 on 2022-08-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uid',
            new_name='uname',
        ),
    ]
